# Generated by Django 4.2.7 on 2023-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
