# Generated by Django 4.2.7 on 2023-11-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_rate_alter_product_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestScrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
