# Generated by Django 4.2.7 on 2023-11-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_requestscrapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=3000)),
                ('director', models.TextField(max_length=3000)),
                ('country', models.TextField(max_length=3000)),
                ('genre', models.TextField(max_length=3000)),
                ('year', models.DateTimeField(auto_now_add=True)),
                ('rate', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
