# Generated by Django 4.2.7 on 2023-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestscrapper',
            name='status',
            field=models.CharField(default='Pendin', max_length=256),
            preserve_default=False,
        ),
    ]
