# Generated by Django 4.2.7 on 2023-11-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_brand_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_year',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
